package stark.dataworks.coderaider.genericagent.core.metrics;

/**
 * TokenUsageTracker implements token usage tracking.
 */
public class TokenUsageTracker
{

    /**
     * Input token count consumed by the model call.
     */
    private int input;

    /**
     * Output token count generated by the model call.
     */
    private int output;

    /**
     * Adds this value.
     *
     * @param usage usage.
     */
    public void add(TokenUsage usage)
    {
        this.input += usage.getInputTokens();
        this.output += usage.getOutputTokens();
    }

    /**
     * Returns an immutable snapshot of current token usage.
     *
     * @return token usage result.
     */
    public TokenUsage snapshot()
    {
        return new TokenUsage(input, output);
    }
}
