package stark.dataworks.coderaider.gundam.core.metrics;

/**
 * TokenUsageTracker implements token usage tracking.
 */
public class TokenUsageTracker
{

    /**
     * Input token count consumed by the model call.
     */
    private int input;

    /**
     * Output token count generated by the model call.
     */
    private int output;

    /**
     * Adds data to internal state consumed by later runtime steps.
     * @param usage The usage used by this operation.
     */
    public void add(TokenUsage usage)
    {
        this.input += usage.getInputTokens();
        this.output += usage.getOutputTokens();
    }

    /**
     * Performs snapshot as part of TokenUsageTracker runtime responsibilities.
     * @return The value produced by this operation.
     */
    public TokenUsage snapshot()
    {
        return new TokenUsage(input, output);
    }
}
